""" Meta {{{
    set nocompatible
    filetype plugin on
""" }}}
""" Simple keybinds {{{
    let mapleader = ","
    nnoremap j gj
    nnoremap k gk
    nnoremap Q :echo("Q is disabled, becuase it sucks.")<Enter>
""" }}}
""" Indentation {{{
    " http://vimcasts.org/episodes/whitespace-preferences-and-filetypes/
    " per-filetype settings take precedence, these are only global fallback defaults
    set tabstop=4
    set softtabstop=4
    set shiftwidth=4
    set expandtab
""" }}}
""" Text Display {{{
    set nowrap
    set foldlevel=99
    set foldmethod=marker
    set listchars=tab:▒░,trail:·,precedes:←,extends:→,nbsp:␣
""" }}}
""" Plugins {{{
    " Load/store plugins from here
    call plug#begin('~/.vim/plugged')
    Plug 'w0rp/ale'
    let g:ale_fixers = { 'rst': ['trim_whitespace'] }
    let g:ale_fix_on_save = 1
    Plug 'NLKNguyen/papercolor-theme'
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    Plug 'tpope/vim-surround'
    Plug 'tpope/vim-commentary'
    Plug 'junegunn/fzf.vim'
    Plug 'editorconfig/editorconfig-vim'
    let g:netrw_banner=0
    let g:netrw_liststyle=3
    let g:airline_theme='papercolor'
    Plug 'rust-lang/rust.vim'
    " Initialize plugin system
    call plug#end()
    " Enable built-in man page viewer plugin
    runtime ftplugin/man.vim
""" }}}
""" Persistent undo {{{
    if has('persistent_undo') && exists('&undodir')
        if !isdirectory($HOME . "/.vim/undo")
            call mkdir($HOME . "/.vim/undo", "p", 0700)
        endif
        set undodir=$HOME/.vim/undo/            " where to store undofiles
        set undofile                            " enable undofile
        set undolevels=500                      " max undos stored
        set undoreload=10000                    " buffer stored undos
    endif
""" }}}
""" Swap files, unless vim is invoked using sudo {{{
    """ https://github.com/tejr/dotfiles/blob/master/vim/vimrc
    if !strlen($SUDO_USER)
        if !isdirectory($HOME . "/.vim/swap")
          call mkdir($HOME . "/.vim/swap", "p", 0700)
        endif
        set directory^=$HOME/.vim/swap/         " default cwd, // full path
        set swapfile                            " enable swap files
        set updatecount=50                      " update swp after 50chars
        """ Don't swap tmp, mount or network dirs {{{
            augroup SwapIgnore
                autocmd! BufNewFile,BufReadPre /tmp/*,/mnt/*,/media/*
                    \ setlocal noswapfile
            augroup END
        """ }}}
    else
        set noswapfile                          " dont swap sudo'ed files
    endif
""" }}}
""" Put viminfo in ~/.vim {{{
    set viminfo+=n~/.vim/viminfo
""" }}}
""" Return to last edit position when opening files {{{
    augroup LastPosition
        autocmd! BufReadPost *
            \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \     exe "normal! g`\"" |
            \ endif
    augroup END
""" }}}
""" Appearance {{{
    set termguicolors
    " these two lines are needed to make colors work in tmux, :help xterm-true-color
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set guioptions=
    set guifont=Input\ Extra-Condensed\ 12
    set background=light
    set cursorline
    set noshowmode " disable mode indicator, since lightline makes it redundant
    set scrolloff=0
    colorscheme PaperColor
""" }}}
""" Search behaviour {{{
    set smartcase " override with \C or \c
    " PSA: The \v switch will give all subsequent characters in a pattern
    " their special regex meaning without requiring backslashes. :help \v
    " Using \V does the opposite, and treats characters literally.
    set hlsearch
""" }}}

